# react build

FROM node:21 AS build

ENV DOMAIN=dev.cream-dream.site

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

# nginx

FROM nginx:latest

RUN apt-get update && apt-get install -y curl certbot python3-certbot-nginx

RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/letsencrypt/live/${DOMAIN}/

# RUN certbot certonly --nginx --non-interactive --agree-tos --email

COPY --from=build /app/build /usr/share/nginx/html

COPY ../nginx.conf /etc/nginx/conf.d/default.conf


EXPOSE 80

# CMD ["nginx", "-g", "daemon off;"]
ENTRYPOINT [ "tail" , "-f" , "/dev/null" ]